### ISSUE TITLE
Search does not load because of missing location

### ISSUE THREAD

**Issue by maxammann** [ehrenamtskarte/ehrenamtskarte#187]
**Describe the bug**
When you open the Search View then nothing loads. This is because `await Geolocator.getCurrentPosition();` never resolves.
This only happens on my phone without google play services installed so far.

**To Reproduce**
1. Use a smartphone without google play services
2. Enable locations services
3. Open the app

**Expected behavior**
The Search page should load

**Stacktraces**

```
W/System.err(11141): java.lang.IllegalArgumentException: provider doesn't exist: network
W/System.err(11141): 	at android.os.Parcel.createException(Parcel.java:2075)
W/System.err(11141): 	at android.os.Parcel.readException(Parcel.java:2039)
W/System.err(11141): 	at android.os.Parcel.readException(Parcel.java:1987)
W/System.err(11141): 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:1151)
W/System.err(11141): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1019)
W/System.err(11141): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:590)
W/System.err(11141): 	at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.requestLocationUpdates(MapboxFusedLocationEngineImpl.java:55)
W/System.err(11141): 	at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.requestLocationUpdates(MapboxFusedLocationEngineImpl.java:22)
W/System.err(11141): 	at com.mapbox.android.core.location.LocationEngineProxy.requestLocationUpdates(LocationEngineProxy.java:34)
W/System.err(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1259)
W/System.err(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.onStart(LocationComponent.java:1197)
W/System.err(11141): 	at com.mapbox.mapboxsdk.maps.MapboxMap.onStart(MapboxMap.java:146)
W/System.err(11141): 	at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:385)
W/System.err(11141): 	at com.mapbox.mapboxgl.MapboxMapController.onActivityStarted(MapboxMapController.java:1047)
W/System.err(11141): 	at android.app.Application.dispatchActivityStarted(Application.java:406)
W/System.err(11141): 	at android.app.Activity.dispatchActivityStarted(Activity.java:1238)
W/System.err(11141): 	at android.app.Activity.onStart(Activity.java:1723)
W/System.err(11141): 	at io.flutter.embedding.android.FlutterActivity.onStart(FlutterActivity.java:535)
W/System.err(11141): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
W/System.err(11141): 	at android.app.Activity.performStart(Activity.java:7847)
W/System.err(11141): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
W/System.err(11141): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
W/System.err(11141): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
W/System.err(11141): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
W/System.err(11141): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
W/System.err(11141): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
W/System.err(11141): 	at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(11141): 	at android.os.Looper.loop(Looper.java:214)
W/System.err(11141): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(11141): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11141): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
W/System.err(11141): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
W/System.err(11141): Caused by: android.os.RemoteException: Remote stack trace:
W/System.err(11141): 	at com.android.server.LocationManagerService.requestLocationUpdatesLocked(LocationManagerService.java:2575)
W/System.err(11141): 	at com.android.server.LocationManagerService.requestLocationUpdates(LocationManagerService.java:2555)
W/System.err(11141): 	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:468)
W/System.err(11141): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
W/System.err(11141): 	at android.os.Binder.execTransact(Binder.java:994)
E/Mbgl-LocationComponent(11141): Failed to obtain last location update
E/Mbgl-LocationComponent(11141): java.lang.Exception: Last location unavailable
E/Mbgl-LocationComponent(11141): 	at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.getLastLocation(MapboxFusedLocationEngineImpl.java:41)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.android.core.location.LocationEngineProxy.getLastLocation(LocationEngineProxy.java:25)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.setLastLocation(LocationComponent.java:1480)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1271)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.onStart(LocationComponent.java:1197)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.maps.MapboxMap.onStart(MapboxMap.java:146)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:385)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxgl.MapboxMapController.onActivityStarted(MapboxMapController.java:1047)
E/Mbgl-LocationComponent(11141): 	at android.app.Application.dispatchActivityStarted(Application.java:406)
E/Mbgl-LocationComponent(11141): 	at android.app.Activity.dispatchActivityStarted(Activity.java:1238)
E/Mbgl-LocationComponent(11141): 	at android.app.Activity.onStart(Activity.java:1723)
E/Mbgl-LocationComponent(11141): 	at io.flutter.embedding.android.FlutterActivity.onStart(FlutterActivity.java:535)
E/Mbgl-LocationComponent(11141): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
E/Mbgl-LocationComponent(11141): 	at android.app.Activity.performStart(Activity.java:7847)
E/Mbgl-LocationComponent(11141): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
E/Mbgl-LocationComponent(11141): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
E/Mbgl-LocationComponent(11141): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
E/Mbgl-LocationComponent(11141): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
E/Mbgl-LocationComponent(11141): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/Mbgl-LocationComponent(11141): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/Mbgl-LocationComponent(11141): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/Mbgl-LocationComponent(11141): 	at android.os.Looper.loop(Looper.java:214)
E/Mbgl-LocationComponent(11141): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/Mbgl-LocationComponent(11141): 	at java.lang.reflect.Method.invoke(Native Method)
E/Mbgl-LocationComponent(11141): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/Mbgl-LocationComponent(11141): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
W/System.err(11141): java.lang.IllegalArgumentException: provider doesn't exist: network
W/System.err(11141): 	at android.os.Parcel.createException(Parcel.java:2075)
W/System.err(11141): 	at android.os.Parcel.readException(Parcel.java:2039)
W/System.err(11141): 	at android.os.Parcel.readException(Parcel.java:1987)
W/System.err(11141): 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:1151)
W/System.err(11141): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1019)
W/System.err(11141): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:590)
W/System.err(11141): 	at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.requestLocationUpdates(MapboxFusedLocationEngineImpl.java:55)
W/System.err(11141): 	at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.requestLocationUpdates(MapboxFusedLocationEngineImpl.java:22)
W/System.err(11141): 	at com.mapbox.android.core.location.LocationEngineProxy.requestLocationUpdates(LocationEngineProxy.java:34)
W/System.err(11141): 	at com.mapbox.mapboxgl.MapboxMapController.startListeningForLocationUpdates(MapboxMapController.java:1249)
W/System.err(11141): 	at com.mapbox.mapboxgl.MapboxMapController.onActivityResumed(MapboxMapController.java:1057)
W/System.err(11141): 	at android.app.Application.dispatchActivityResumed(Application.java:436)
W/System.err(11141): 	at android.app.Activity.dispatchActivityResumed(Activity.java:1269)
W/System.err(11141): 	at android.app.Activity.onResume(Activity.java:1795)
W/System.err(11141): 	at io.flutter.embedding.android.FlutterActivity.onResume(FlutterActivity.java:542)
W/System.err(11141): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
W/System.err(11141): 	at android.app.Activity.performResume(Activity.java:7958)
W/System.err(11141): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
W/System.err(11141): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
W/System.err(11141): 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
W/System.err(11141): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
W/System.err(11141): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
W/System.err(11141): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
W/System.err(11141): 	at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(11141): 	at android.os.Looper.loop(Looper.java:214)
W/System.err(11141): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(11141): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11141): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
W/System.err(11141): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)


W/GooglePlayServicesUtil(11141): Google Play Store is missing.
W/GooglePlayServicesUtil(11141): Google Play Store is missing.
W/System.err(11141): java.lang.IllegalArgumentException: provider doesn't exist: network
W/System.err(11141): 	at android.os.Parcel.createException(Parcel.java:2075)
W/System.err(11141): 	at android.os.Parcel.readException(Parcel.java:2039)
W/System.err(11141): 	at android.os.Parcel.readException(Parcel.java:1987)
W/System.err(11141): 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:1151)
W/System.err(11141): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1019)
W/System.err(11141): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:590)
W/System.err(11141): 	at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.requestLocationUpdates(MapboxFusedLocationEngineImpl.java:55)
W/System.err(11141): 	at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.requestLocationUpdates(MapboxFusedLocationEngineImpl.java:22)
W/System.err(11141): 	at com.mapbox.android.core.location.LocationEngineProxy.requestLocationUpdates(LocationEngineProxy.java:34)
W/System.err(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1259)
W/System.err(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.enableLocationComponent(LocationComponent.java:1387)
W/System.err(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(LocationComponent.java:516)
W/System.err(11141): 	at com.mapbox.mapboxgl.MapboxMapController.enableLocationComponent(MapboxMapController.java:384)
W/System.err(11141): 	at com.mapbox.mapboxgl.MapboxMapController.access$600(MapboxMapController.java:97)
W/System.err(11141): 	at com.mapbox.mapboxgl.MapboxMapController$1.onStyleLoaded(MapboxMapController.java:363)
W/System.err(11141): 	at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:959)
W/System.err(11141): 	at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:221)
W/System.err(11141): 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1328)
W/System.err(11141): 	at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
W/System.err(11141): 	at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1106)
W/System.err(11141): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(11141): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err(11141): 	at android.os.Looper.loop(Looper.java:174)
W/System.err(11141): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(11141): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11141): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
W/System.err(11141): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
W/System.err(11141): Caused by: android.os.RemoteException: Remote stack trace:
W/System.err(11141): 	at com.android.server.LocationManagerService.requestLocationUpdatesLocked(LocationManagerService.java:2575)
W/System.err(11141): 	at com.android.server.LocationManagerService.requestLocationUpdates(LocationManagerService.java:2555)
W/System.err(11141): 	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:468)
W/System.err(11141): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
W/System.err(11141): 	at android.os.Binder.execTransact(Binder.java:994)
E/Mbgl-LocationComponent(11141): Failed to obtain last location update
E/Mbgl-LocationComponent(11141): java.lang.Exception: Last location unavailable
E/Mbgl-LocationComponent(11141): 	at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.getLastLocation(MapboxFusedLocationEngineImpl.java:41)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.android.core.location.LocationEngineProxy.getLastLocation(LocationEngineProxy.java:25)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.setLastLocation(LocationComponent.java:1480)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1271)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.enableLocationComponent(LocationComponent.java:1387)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(LocationComponent.java:516)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxgl.MapboxMapController.enableLocationComponent(MapboxMapController.java:384)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxgl.MapboxMapController.access$600(MapboxMapController.java:97)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxgl.MapboxMapController$1.onStyleLoaded(MapboxMapController.java:363)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:959)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:221)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1328)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1106)
E/Mbgl-LocationComponent(11141): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/Mbgl-LocationComponent(11141): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/Mbgl-LocationComponent(11141): 	at android.os.Looper.loop(Looper.java:174)
E/Mbgl-LocationComponent(11141): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/Mbgl-LocationComponent(11141): 	at java.lang.reflect.Method.invoke(Native Method)
E/Mbgl-LocationComponent(11141): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/Mbgl-LocationComponent(11141): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
E/Mbgl-LocationComponent(11141): Failed to obtain last location update
E/Mbgl-LocationComponent(11141): java.lang.Exception: Last location unavailable
E/Mbgl-LocationComponent(11141): 	at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.getLastLocation(MapboxFusedLocationEngineImpl.java:41)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.android.core.location.LocationEngineProxy.getLastLocation(LocationEngineProxy.java:25)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.setLastLocation(LocationComponent.java:1480)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.setLocationEngine(LocationComponent.java:1009)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxgl.MapboxMapController.enableLocationComponent(MapboxMapController.java:386)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxgl.MapboxMapController.access$600(MapboxMapController.java:97)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxgl.MapboxMapController$1.onStyleLoaded(MapboxMapController.java:363)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:959)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:221)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1328)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
E/Mbgl-LocationComponent(11141): 	at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1106)
E/Mbgl-LocationComponent(11141): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/Mbgl-LocationComponent(11141): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/Mbgl-LocationComponent(11141): 	at android.os.Looper.loop(Looper.java:174)
E/Mbgl-LocationComponent(11141): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/Mbgl-LocationComponent(11141): 	at java.lang.reflect.Method.invoke(Native Method)
E/Mbgl-LocationComponent(11141): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/Mbgl-LocationComponent(11141): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
W/System.err(11141): java.lang.IllegalArgumentException: provider doesn't exist: network
W/System.err(11141): 	at android.os.Parcel.createException(Parcel.java:2075)
W/System.err(11141): 	at android.os.Parcel.readException(Parcel.java:2039)
W/System.err(11141): 	at android.os.Parcel.readException(Parcel.java:1987)
W/System.err(11141): 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:1151)
W/System.err(11141): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1019)
W/System.err(11141): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:590)
W/System.err(11141): 	at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.requestLocationUpdates(MapboxFusedLocationEngineImpl.java:55)
W/System.err(11141): 	at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.requestLocationUpdates(MapboxFusedLocationEngineImpl.java:22)
W/System.err(11141): 	at com.mapbox.android.core.location.LocationEngineProxy.requestLocationUpdates(LocationEngineProxy.java:34)
W/System.err(11141): 	at com.mapbox.mapboxsdk.location.LocationComponent.setLocationEngine(LocationComponent.java:1010)
W/System.err(11141): 	at com.mapbox.mapboxgl.MapboxMapController.enableLocationComponent(MapboxMapController.java:386)
W/System.err(11141): 	at com.mapbox.mapboxgl.MapboxMapController.access$600(MapboxMapController.java:97)
W/System.err(11141): 	at com.mapbox.mapboxgl.MapboxMapController$1.onStyleLoaded(MapboxMapController.java:363)
W/System.err(11141): 	at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:959)
W/System.err(11141): 	at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:221)
W/System.err(11141): 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1328)
W/System.err(11141): 	at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
W/System.err(11141): 	at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1106)
W/System.err(11141): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(11141): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err(11141): 	at android.os.Looper.loop(Looper.java:174)
W/System.err(11141): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(11141): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11141): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
W/System.err(11141): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by maxammann** [comment]
We have now a floss version which is also on f-droid. Users like me should switch :P
