### ISSUE TITLE
GraphiQL causes crash

### ISSUE THREAD

**Issue by maxammann** [ehrenamtskarte/ehrenamtskarte#351]
**Describe the bug**
GraphiQL is causing this error:

```
Apr 25 10:02:34 ehrenamtskarte backend[16007]: kotlin.TypeCastException: null cannot be cast to non-null type kotlin.collections.Map<kotlin.String, kotlin.Any>
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at app.ehrenamtskarte.backend.common.webservice.GraphQLHandler.handle(GraphQLHandler.kt:128)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at app.ehrenamtskarte.backend.common.webservice.WebService$start$1.handle(WebService.kt:55)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:49)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.Server.handle(Server.java:501)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
Apr 25 10:02:34 ehrenamtskarte backend[16007]:         at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Schedulaar** [comment]
Closed with #352
